# Generated by Django 3.2.8 on 2021-10-10 12:22

from django.db import migrations, models
import django.utils.timezone
import s3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=s3.models.user_directory_path)),
                ('image_caption', models.CharField(default='Photo by demo', max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
